//! The macOS and Linux cleaning catalog.
//!
//! `%CACHE%` is `~/Library/Caches` on macOS and `$XDG_CACHE_HOME` (usually
//! `~/.cache`) on Linux; `%CONFIG%` is `~/Library/Application Support` or
//! `$XDG_CONFIG_HOME`; `%DATA%` is `$XDG_DATA_HOME`. Where the two systems
//! use different folder names, `os!` picks the right one.

use super::rules::{Group::*, Rule, Target::*};
use super::unix;
use super::Special::Tool;

#[cfg(target_os = "macos")]
macro_rules! os {
    (mac: $m:expr, linux: $l:expr) => {
        $m
    };
}
#[cfg(not(target_os = "macos"))]
macro_rules! os {
    (mac: $m:expr, linux: $l:expr) => {
        $l
    };
}

#[cfg(target_os = "macos")]
const SYSTEM: [Rule; 2] = [
    Rule {
        id: "sys.logs",
        group: System,
        app: "macOS",
        name: "Old logs & crash reports",
        about: "Log files and crash reports your apps wrote more than a week ago.",
        default_on: true,
        admin: false,
        warning: None,
        close: &[],
        targets: &[Older("%HOME%/Library/Logs", 168)],
    },
    Rule {
        id: "sys.trash",
        group: System,
        app: "macOS",
        name: "Trash",
        about: "Everything in the Trash. (Heft needs Full Disk Access in System Settings to see inside it.)",
        default_on: false,
        admin: false,
        warning: Some("Permanently deletes everything in the Trash."),
        close: &[],
        targets: &[Path("%HOME%/.Trash")],
    },
];

#[cfg(target_os = "linux")]
const SYSTEM: [Rule; 7] = [
    Rule {
        id: "sys.thumbs",
        group: System,
        app: "Linux",
        name: "Thumbnail cache",
        about: "Picture and video previews. File managers recreate them as you browse.",
        default_on: true,
        admin: false,
        warning: None,
        close: &[],
        targets: &[Path("%CACHE%/thumbnails")],
    },
    Rule {
        id: "sys.trash",
        group: System,
        app: "Linux",
        name: "Trash",
        about: "Everything in your Trash.",
        default_on: false,
        admin: false,
        warning: Some("Permanently deletes everything in the Trash."),
        close: &[],
        targets: &[Path("%DATA%/Trash/files"), Path("%DATA%/Trash/info"), Path("%DATA%/Trash/expunged")],
    },
    Rule {
        id: "sys.apt",
        group: System,
        app: "Linux",
        name: "APT package cache",
        about: "Installer packages apt already used. Runs `apt-get clean`.",
        default_on: true,
        admin: true,
        warning: None,
        close: &["apt", "apt-get", "dpkg", "unattended-upgr"],
        targets: &[Special(Tool(unix::apt))],
    },
    Rule {
        id: "sys.dnf",
        group: System,
        app: "Linux",
        name: "DNF package cache",
        about: "Installer packages dnf kept. Runs `dnf clean packages`.",
        default_on: true,
        admin: true,
        warning: None,
        close: &["dnf", "packagekitd"],
        targets: &[Special(Tool(unix::dnf))],
    },
    Rule {
        id: "sys.journal",
        group: System,
        app: "Linux",
        name: "Old system logs",
        about: "Archived systemd journal files older than two weeks. Runs `journalctl --vacuum-time=2weeks`.",
        default_on: true,
        admin: true,
        warning: None,
        close: &[],
        targets: &[Special(Tool(unix::journald))],
    },
    Rule {
        id: "sys.snap",
        group: System,
        app: "Linux",
        name: "Old snap revisions",
        about: "Snap keeps the previous version of every snap after it updates. Removes those disabled revisions.",
        default_on: false,
        admin: true,
        warning: Some("Those snaps can't be rolled back to their previous version afterwards."),
        close: &[],
        targets: &[Special(Tool(unix::snap))],
    },
    Rule {
        id: "sys.flatpak",
        group: System,
        app: "Linux",
        name: "Unused Flatpak runtimes",
        about: "Runtimes and extensions no installed app needs. Runs `flatpak uninstall --unused`; the size is Heft's estimate.",
        default_on: true,
        admin: false,
        warning: None,
        close: &[],
        targets: &[Special(Tool(unix::flatpak))],
    },
];

#[cfg(not(any(target_os = "macos", target_os = "linux")))]
const SYSTEM: [Rule; 0] = [];

const BROWSERS: [Rule; 8] = [
    Rule {
        id: "chrome.cache",
        group: Browsers,
        app: "Google Chrome",
        name: "Cache",
        about: "Downloaded copies of web pages, images and scripts. Sites load them again as needed.",
        default_on: true,
        admin: false,
        warning: None,
        close: &["google chrome", "chrome"],
        targets: &[Path(os!(mac: "%CACHE%/Google/Chrome", linux: "%CACHE%/google-chrome"))],
    },
    Rule {
        id: "edge.cache",
        group: Browsers,
        app: "Microsoft Edge",
        name: "Cache",
        about: "Downloaded copies of web pages, images and scripts. Sites load them again as needed.",
        default_on: true,
        admin: false,
        warning: None,
        close: &["microsoft edge", "msedge"],
        targets: &[Path(os!(mac: "%CACHE%/Microsoft Edge", linux: "%CACHE%/microsoft-edge"))],
    },
    Rule {
        id: "firefox.cache",
        group: Browsers,
        app: "Mozilla Firefox",
        name: "Cache",
        about: "Downloaded copies of web pages, images and scripts. Sites load them again as needed.",
        default_on: true,
        admin: false,
        warning: None,
        close: &["firefox", "firefox-bin"],
        targets: &[
            EachDir(os!(mac: "%CACHE%/Firefox/Profiles", linux: "%CACHE%/mozilla/firefox"), "cache2"),
            EachDir(os!(mac: "%CACHE%/Firefox/Profiles", linux: "%CACHE%/mozilla/firefox"), "startupCache"),
            EachDir(os!(mac: "%CACHE%/Firefox/Profiles", linux: "%CACHE%/mozilla/firefox"), "thumbnails"),
        ],
    },
    Rule {
        id: "brave.cache",
        group: Browsers,
        app: "Brave",
        name: "Cache",
        about: "Downloaded copies of web pages, images and scripts. Sites load them again as needed.",
        default_on: true,
        admin: false,
        warning: None,
        close: &["brave browser", "brave"],
        targets: &[Path("%CACHE%/BraveSoftware/Brave-Browser")],
    },
    Rule {
        id: "chromium.cache",
        group: Browsers,
        app: "Chromium",
        name: "Cache",
        about: "Downloaded copies of web pages, images and scripts. Sites load them again as needed.",
        default_on: true,
        admin: false,
        warning: None,
        close: &["chromium"],
        targets: &[Path(os!(mac: "%CACHE%/Chromium", linux: "%CACHE%/chromium"))],
    },
    Rule {
        id: "vivaldi.cache",
        group: Browsers,
        app: "Vivaldi",
        name: "Cache",
        about: "Downloaded copies of web pages, images and scripts. Sites load them again as needed.",
        default_on: true,
        admin: false,
        warning: None,
        close: &["vivaldi", "vivaldi-bin"],
        targets: &[Path(os!(mac: "%CACHE%/Vivaldi", linux: "%CACHE%/vivaldi"))],
    },
    Rule {
        id: "opera.cache",
        group: Browsers,
        app: "Opera",
        name: "Cache",
        about: "Downloaded copies of web pages, images and scripts. Sites load them again as needed.",
        default_on: true,
        admin: false,
        warning: None,
        close: &["opera"],
        targets: &[Path(os!(mac: "%CACHE%/com.operasoftware.Opera", linux: "%CACHE%/opera"))],
    },
    Rule {
        id: "safari.cache",
        group: Browsers,
        app: "Safari",
        name: "Cache",
        about: "Safari's web cache. (Heft needs Full Disk Access in System Settings to see it.)",
        default_on: true,
        admin: false,
        warning: None,
        close: &["safari"],
        targets: &[Path("%CACHE%/com.apple.Safari")],
    },
];

const APPS: [Rule; 7] = [
    Rule {
        id: "app.discord",
        group: Apps,
        app: "Discord",
        name: "Cache",
        about: "Images, videos and scripts Discord downloaded.",
        default_on: true,
        admin: false,
        warning: None,
        close: &["discord"],
        targets: &[Path("%CONFIG%/discord/Cache"), Path("%CONFIG%/discord/Code Cache"), Path("%CONFIG%/discord/GPUCache")],
    },
    Rule {
        id: "app.slack",
        group: Apps,
        app: "Slack",
        name: "Cache",
        about: "Files and pages Slack downloaded.",
        default_on: true,
        admin: false,
        warning: None,
        close: &["slack"],
        targets: &[
            Path("%CONFIG%/Slack/Cache"),
            Path("%CONFIG%/Slack/Code Cache"),
            Path("%CONFIG%/Slack/GPUCache"),
            Path("%CONFIG%/Slack/Service Worker/CacheStorage"),
        ],
    },
    Rule {
        id: "app.vscode",
        group: Apps,
        app: "Visual Studio Code",
        name: "Cache & old logs",
        about: "Editor caches, downloaded extension packages, and logs older than a week.",
        default_on: true,
        admin: false,
        warning: None,
        close: &["code", "electron"],
        targets: &[
            Path("%CONFIG%/Code/Cache"),
            Path("%CONFIG%/Code/CachedData"),
            Path("%CONFIG%/Code/Code Cache"),
            Path("%CONFIG%/Code/GPUCache"),
            Path("%CONFIG%/Code/CachedExtensionVSIXs"),
            Older("%CONFIG%/Code/logs", 168),
        ],
    },
    Rule {
        id: "app.cursor",
        group: Apps,
        app: "Cursor",
        name: "Cache & old logs",
        about: "Editor caches, downloaded extension packages, and logs older than a week.",
        default_on: true,
        admin: false,
        warning: None,
        close: &["cursor"],
        targets: &[
            Path("%CONFIG%/Cursor/Cache"),
            Path("%CONFIG%/Cursor/CachedData"),
            Path("%CONFIG%/Cursor/Code Cache"),
            Path("%CONFIG%/Cursor/GPUCache"),
            Path("%CONFIG%/Cursor/CachedExtensionVSIXs"),
            Older("%CONFIG%/Cursor/logs", 168),
        ],
    },
    Rule {
        id: "app.spotify",
        group: Apps,
        app: "Spotify",
        name: "Cache",
        about: "Streaming cache. Songs you downloaded for offline listening are kept.",
        default_on: true,
        admin: false,
        warning: None,
        close: &["spotify"],
        targets: &[Path(os!(mac: "%CACHE%/com.spotify.client/Data", linux: "%CACHE%/spotify/Data"))],
    },
    Rule {
        id: "app.steam",
        group: Apps,
        app: "Steam",
        name: "Web cache",
        about: "The Steam client's web cache. Games are not touched.",
        default_on: true,
        admin: false,
        warning: None,
        close: &["steam", "steamwebhelper", "steam_osx"],
        targets: &[Path(os!(mac: "%CONFIG%/Steam/appcache/httpcache", linux: "%DATA%/Steam/appcache/httpcache"))],
    },
    Rule {
        id: "app.jetbrains",
        group: Apps,
        app: "JetBrains IDEs",
        name: "Caches & indexes",
        about: "IntelliJ IDEA, PyCharm, Rider, WebStorm, CLion, GoLand and RustRover caches.",
        default_on: false,
        admin: false,
        warning: Some("Projects are re-indexed the next time you open them."),
        close: &["idea", "pycharm", "rider", "webstorm", "clion", "goland", "rustrover", "java"],
        targets: &[Path("%CACHE%/JetBrains")],
    },
];

const DEVELOPER: [Rule; 9] = [
    Rule {
        id: "dev.homebrew",
        group: Developer,
        app: "Homebrew",
        name: "Downloads & old versions",
        about: "Homebrew's download cache and superseded versions of installed packages. Runs `brew cleanup --prune=all`.",
        default_on: true,
        admin: false,
        warning: None,
        close: &["brew"],
        targets: &[Special(Tool(unix::homebrew))],
    },
    Rule {
        id: "dev.npm",
        group: Developer,
        app: "npm",
        name: "Package cache",
        about: "Every package npm has downloaded, plus npx installs and logs.",
        default_on: false,
        admin: false,
        warning: Some("Packages download again the next time a project installs them."),
        close: &[],
        targets: &[Path("%HOME%/.npm/_cacache"), Path("%HOME%/.npm/_npx"), Path("%HOME%/.npm/_logs")],
    },
    Rule {
        id: "dev.yarn",
        group: Developer,
        app: "Yarn",
        name: "Package cache",
        about: "Yarn's global cache.",
        default_on: false,
        admin: false,
        warning: Some("Packages download again the next time a project installs them."),
        close: &[],
        targets: &[Path(os!(mac: "%CACHE%/Yarn", linux: "%CACHE%/yarn"))],
    },
    Rule {
        id: "dev.bun",
        group: Developer,
        app: "Bun",
        name: "Package cache",
        about: "Bun's global install cache.",
        default_on: false,
        admin: false,
        warning: Some("Packages download again the next time a project installs them."),
        close: &[],
        targets: &[Path("%HOME%/.bun/install/cache")],
    },
    Rule {
        id: "dev.pip",
        group: Developer,
        app: "pip",
        name: "Package cache",
        about: "Wheels and downloads pip keeps between installs.",
        default_on: false,
        admin: false,
        warning: Some("Packages download again the next time you install them."),
        close: &[],
        targets: &[Path("%CACHE%/pip")],
    },
    Rule {
        id: "dev.cargo",
        group: Developer,
        app: "Cargo (Rust)",
        name: "Registry & git caches",
        about: "Downloaded crates, their unpacked sources, and git checkouts. Build folders (target) are listed under Disk usage › Build junk.",
        default_on: false,
        admin: false,
        warning: Some("Crates download again the next time you build."),
        close: &["cargo"],
        targets: &[
            Path("%CARGO_HOME%/registry/cache"),
            Path("%CARGO_HOME%/registry/src"),
            Path("%CARGO_HOME%/git/checkouts"),
        ],
    },
    Rule {
        id: "dev.go",
        group: Developer,
        app: "Go",
        name: "Build cache",
        about: "Compiled packages the go command reuses between builds.",
        default_on: false,
        admin: false,
        warning: Some("The next build of each project is slower."),
        close: &["go"],
        targets: &[Path("%CACHE%/go-build")],
    },
    Rule {
        id: "dev.gradle",
        group: Developer,
        app: "Gradle",
        name: "Caches",
        about: "Downloaded dependencies and build caches in the Gradle user home.",
        default_on: false,
        admin: false,
        warning: Some("Dependencies download again on the next build."),
        close: &[],
        targets: &[Path("%GRADLE_USER_HOME%/caches")],
    },
    Rule {
        id: "dev.electron",
        group: Developer,
        app: "Electron",
        name: "Download caches",
        about: "Electron binaries downloaded by electron and electron-builder.",
        default_on: false,
        admin: false,
        warning: None,
        close: &[],
        targets: &[Path("%CACHE%/electron"), Path("%CACHE%/electron-builder")],
    },
];

#[cfg(target_os = "macos")]
const XCODE: [Rule; 5] = [
    Rule {
        id: "xcode.derived",
        group: Developer,
        app: "Xcode",
        name: "DerivedData & previews",
        about: "Build products, indexes and SwiftUI preview caches.",
        default_on: false,
        admin: false,
        warning: Some("Projects rebuild from scratch and re-index the next time you open them."),
        close: &["xcode"],
        targets: &[
            Path("%HOME%/Library/Developer/Xcode/DerivedData"),
            Path("%HOME%/Library/Developer/Xcode/UserData/Previews"),
        ],
    },
    Rule {
        id: "xcode.simulators",
        group: Developer,
        app: "Xcode",
        name: "Unavailable simulators",
        about: "Simulators whose iOS, watchOS or tvOS runtime is no longer installed, so they can't run anyway. Runs `xcrun simctl delete unavailable`.",
        default_on: true,
        admin: false,
        warning: None,
        close: &["simulator"],
        targets: &[Special(Tool(unix::simulators))],
    },
    Rule {
        id: "xcode.simcache",
        group: Developer,
        app: "Xcode",
        name: "Simulator caches",
        about: "Caches the simulators rebuild when they next start.",
        default_on: true,
        admin: false,
        warning: None,
        close: &["simulator"],
        targets: &[Path("%HOME%/Library/Developer/CoreSimulator/Caches")],
    },
    Rule {
        id: "xcode.devicesupport",
        group: Developer,
        app: "Xcode",
        name: "Device support files",
        about: "Debug symbols Xcode copied from every iPhone, iPad, Watch and Apple TV you've connected.",
        default_on: false,
        admin: false,
        warning: Some("Xcode copies them again (a few minutes) the next time you connect that device."),
        close: &["xcode"],
        targets: &[
            Path("%HOME%/Library/Developer/Xcode/iOS DeviceSupport"),
            Path("%HOME%/Library/Developer/Xcode/watchOS DeviceSupport"),
            Path("%HOME%/Library/Developer/Xcode/tvOS DeviceSupport"),
        ],
    },
    Rule {
        id: "dev.cocoapods",
        group: Developer,
        app: "CocoaPods",
        name: "Pod cache",
        about: "Pods CocoaPods downloaded.",
        default_on: false,
        admin: false,
        warning: Some("Pods download again the next time you run pod install."),
        close: &[],
        targets: &[Path("%CACHE%/CocoaPods")],
    },
];

/// All rules for this OS, in display order.
pub fn catalog() -> Vec<Rule> {
    let mut v = Vec::new();
    v.extend(SYSTEM);
    v.extend(BROWSERS);
    v.extend(APPS);
    #[cfg(target_os = "macos")]
    v.extend(XCODE);
    v.extend(DEVELOPER);
    v
}
